### ISSUE TITLE
Captcha copy/paste issue

### ISSUE THREAD

**Issue by rhino36** [zixaphir/appchan-x#836]
I get this sometimes. Instead of the whole "I'm not a robot" thing, I get a captcha and a text box under. After I enter the captcha, it asks me to copy and paste some code. I don't know if a button is missing or if I'm stupid, but after copying the code, I have no idea what to do. Pressing enter just skips a line, waiting does not do anything
![dikbut](https://cloud.githubusercontent.com/assets/7881445/5377764/002b5f20-8053-11e4-97ec-d1cb3daec40f.png)
This is what it looks like

**Comment by zixaphir** [comment]
This should be fixed now.

**Comment by Gabriel210** [comment]
I found a solution!! : It gave the exact same problem for me in google chrome, however using Mozilla to get the key, went without a problem, because for some reason the captcha gave me a different way to verify that I'm not a robot. (It asked me to click on pictures, like click on the picture that contains a pizza, after that it gave me the key.)
